spring:
  datasource:
    url: jdbc:mysql://101.33.248.42:3317/ddu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hlncsu1071686408ddu
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  #redis 配置
  redis:
    database: 0
    host: 101.33.248.42
    port: 6331
    password: dt7tWNP7t
  #rabbitmq
  rabbitmq:
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    host: 101.33.248.42 #ip
    port: 5663      #端口
    username: lina #账号
    password: binv123456 #密码
server:
  port: 8074
  ssl:
    key-store: classpath:8570726_daydaypipe.top.jks
    key-store-password: 8YUEwwGu
    key-store-type: JKS

logging:
  config: classpath:loggingprod-config.xml


