spring:
  datasource:
    url: jdbc:mysql://101.33.248.42:3317/ddu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hlncsu1071686408ddu
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  #redis 配置
  redis:
    database: 0
    host: 101.33.248.42
    port: 6331
    password: dt7tWNP7t
  #rabbitmq
  rabbitmq:
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    host: 192.168.245.100 #ip
    port: 5672      #端口
    username: admin #账号
    password: 123456 #密码
server:
  port: 8808



