spring:
  redis:
    database: 0
    host: 101.33.248.42
    port: 6331
    password: dt7tWNP7t
  rabbitmq:
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    host: 192.168.245.100 #ip
    port: 5672      #端口
    username: admin #账号
    password: 123456 #密码
netty:
  port: 8084